### ISSUE TITLE
211i max more control

### ISSUE THREAD

**Issue by dominiclapointe** [dahlb/ha_blueair#161]
Hi, ive just enabled your plugin in order to control my Blue Pure 211i max.

Is it possible to have the fan speed exposed? I can see if the fan is on or off but not see (nor control) the speed of it.

Also (less important), would it be possible to control the LED intensity (0% / 100%).

Lastly, my Blue Pure 411i max does show a VOC sensor which my 211i doesnt have, what is this?

Thank you

**Comment by MeeperBeeper** [comment]
I'm not the dev but this might help.

If you find that clicking on the entity in your UI and are able to control the fan speed in the box that pops up, then it's just the card entity that needs to change.  I had the same issue and I found that slider-entity-row from HACS gives you a slider you can use instead of an on/off switch without having to open the entity.
You can view more details and screenshots here: https://github.com/thomasloven/lovelace-slider-entity-row

Note: I found I had to set the max value to 100.1 to allow the slider to reach max speed.  You can read more about that issue here:
https://github.com/thomasloven/lovelace-slider-entity-row/issues/301

As for what VOCs are.  It's volatile organic compounds and you can read more from the BA website:
https://www.blueair.com/us/blog-all/pollutants/vocs-odors-gases.html
